language: node_js
node_js:
  - "7"

script: echo "Running tests against $(node -v) ..."

stages:
  - compile
  - test
  - name: npm release
    if: branch = master

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: compile
      name: "NPM Compile"
      script: echo "Compile Package"
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: "$NPM_API_KEY"

# jobs:
#   include:
#     - stage: "Tests"
#       name: "Unit Tests"
#       script: npm test
#       name: "Just Tests"
#       script: echo "Testing this out"
#     - stage: release to npm
#       name: "NPM Release"
#       script: echo "Build release"
      # provider: npm
      # email: "YOUR_EMAIL_ADDRESS"
      # api_key: "YOUR_AUTH_TOKEN"
