language: node_js
node_js:
  - "7"

script: echo "Running tests against $(node -v) ..."

stages:
  - test
  - release to npm

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm test
      name: "Just Tests"
      script: echo "Testing this out"
    - stage: release to npm
      name: "NPM Release"
      script: echo "Build release"
      script: 'curl http://validstate.herokuapp.com'
      # provider: npm
      # email: "YOUR_EMAIL_ADDRESS"
      # api_key: "YOUR_AUTH_TOKEN"
