language: node_js
node_js:
  - "7"

script: echo "Running tests against $(node -v) ..."

stages:
  - test
  # - name: npm release
  #   if: branch = master

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: npm test
      # Save for later in case we want to add this in
#     - stage: npm release
#       script: echo "Building distrubtion ..." && npm build
#       script: echo "Deploying to npm ..."
#       deploy:
#         provider: npm
#         api_key: "$NPM_API_KEY"
#         on:
#           tags: true
#           skip_cleanup: true
