language: node_js
node_js:
  - "7"

script: echo "Running tests against $(node -v) ..."

stages:
  - test

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"
      script: npm test
